-------------------------------------------------------------------
-------------------CONTROL DE TRANSACCIONES------------------------
-------------------------------------------------------------------


-- Verificar estado inicial
SELECT ID_PRESTAMO, ID_MIEMBRO, ESTADO 
FROM PRESTAMOS_CRAM 
WHERE ID_MIEMBRO = 237;

-- Iniciar transaccion
SAVEPOINT ANTES_PRESTAMO;

-- Insertar nuevo prestamo
INSERT INTO PRESTAMOS_CRAM(ID_PRESTAMO,ID_MIEMBRO,ISBN,ID_BIBLIOTECA,
    FECHA_PRESTAMO,FECHA_LIMITE,FECHA_DEVOLUCION,ESTADO)
VALUES(PRE_CRAM_ID_PRE_SEQ.NEXTVAL,237,9780333783047,26,
    '31/05/2026','21/06/2026',NULL,'Activo');

-- Verificar que se inserto correctamente
SELECT ID_PRESTAMO, ID_MIEMBRO, ISBN, ESTADO 
FROM PRESTAMOS_CRAM 
WHERE ID_MIEMBRO = 237;

-- Confirmar la transaccion permanentemente
COMMIT;

-- Verificar que persiste despues del commit
SELECT ID_PRESTAMO, ID_MIEMBRO, ISBN, ESTADO 
FROM PRESTAMOS_CRAM 
WHERE ID_MIEMBRO = 237;


-- =============================================
-- ESCENARIO 2: ROLLBACK TOTAL
-- Intentar registrar una multa incorrecta
-- y deshacer toda la operacion
-- =============================================

-- Verificar estado inicial de multas
SELECT ID_MULTA, ID_PRESTAMO, MONTO, PAGADA 
FROM MULTAS_CRAM;

-- Insertar multa con monto incorrecto
INSERT INTO MULTAS_CRAM(ID_MULTA,ID_PRESTAMO,ID_MIEMBRO,
    MONTO,FECHA_MULTA,PAGADA,FECHA_PAGO)
VALUES(MUL_CRAM_ID_MUL_SEQ.NEXTVAL,1,182,
    99999,'31/05/2026','N',NULL);

-- Verificar que aparece el registro incorrecto
SELECT ID_MULTA, ID_PRESTAMO, MONTO 
FROM MULTAS_CRAM 
ORDER BY ID_MULTA DESC;

-- Se detecto el error: monto incorrecto
-- Deshacer toda la transaccion
ROLLBACK;

-- Verificar que el registro fue eliminado
SELECT ID_MULTA, ID_PRESTAMO, MONTO 
FROM MULTAS_CRAM 
ORDER BY ID_MULTA DESC;


-- =============================================
-- ESCENARIO 3: SAVEPOINT + ROLLBACK PARCIAL
-- Actualizar estado de prestamo y registrar
-- devolucion, pero solo revertir la multa
-- si fue un error, conservando la devolucion
-- =============================================

-- Verificar estado inicial
SELECT ID_PRESTAMO, ID_MIEMBRO, ESTADO, FECHA_DEVOLUCION 
FROM PRESTAMOS_CRAM 
WHERE ID_PRESTAMO = 51;

-- Paso 1: Registrar devolucion del libro
UPDATE PRESTAMOS_CRAM
SET FECHA_DEVOLUCION = '31/05/2026',
    ESTADO = 'Devuelto'
WHERE ID_PRESTAMO = 51;

-- Verificar actualizacion
SELECT ID_PRESTAMO, ESTADO, FECHA_DEVOLUCION 
FROM PRESTAMOS_CRAM 
WHERE ID_PRESTAMO = 51;

-- Guardar punto de control DESPUES de la devolucion
SAVEPOINT DEVOLUCION_OK;

-- Paso 2: Intentar registrar multa (error: no corresponde multa)
INSERT INTO MULTAS_CRAM(ID_MULTA,ID_PRESTAMO,ID_MIEMBRO,
    MONTO,FECHA_MULTA,PAGADA,FECHA_PAGO)
VALUES(MUL_CRAM_ID_MUL_SEQ.NEXTVAL,51,232,
    150,'31/05/2026','N',NULL);

-- Verificar que se inserto la multa
SELECT ID_MULTA, ID_PRESTAMO, MONTO 
FROM MULTAS_CRAM 
ORDER BY ID_MULTA DESC;

-- Se detecto que la multa fue un error
-- Revertir SOLO la multa, conservar la devolucion
ROLLBACK TO SAVEPOINT DEVOLUCION_OK;

-- Verificar: devolucion persiste, multa revertida
SELECT ID_PRESTAMO, ESTADO, FECHA_DEVOLUCION 
FROM PRESTAMOS_CRAM 
WHERE ID_PRESTAMO = 51;

SELECT ID_MULTA, ID_PRESTAMO, MONTO 
FROM MULTAS_CRAM 
ORDER BY ID_MULTA DESC;

-- Confirmar definitivamente la devolucion
COMMIT;


-- =============================================
-- CUADERNILLO DE CONSULTAS - LIBRERIA CRAM
-- =============================================

--(1)
--Obtener el nombre completo de todos los miembros
--junto con su ciudad y estado de residencia
SELECT M.NOMBRE, M.APELLIDO, D.CIUDAD, D.ESTADO
FROM MIEMBROS_CRAM M
JOIN DIRECCIONES_CRAM D ON M.ID_DIRECCION = D.ID_DIRECCION
ORDER BY M.APELLIDO;

--(2)
--Mostrar todos los libros con el nombre de su editorial
--y su calificacion en Amazon ordenados de mayor a menor calificacion
SELECT L.TITULO, E.NOMBRE_EDITORIAL, L.CALIFICACION_AMAZON
FROM LIBROS_CRAM L
JOIN EDITORIALES_CRAM E ON L.ID_EDITORIAL = E.ID_EDITORIAL
ORDER BY L.CALIFICACION_AMAZON DESC;

--(3)
--Listar todos los prestamos activos mostrando el nombre
--del miembro, titulo del libro y biblioteca donde fue prestado
SELECT M.NOMBRE, M.APELLIDO, L.TITULO, 
       B.NOMBRE_BIBLIOTECA, P.FECHA_LIMITE
FROM PRESTAMOS_CRAM P
JOIN MIEMBROS_CRAM M ON P.ID_MIEMBRO = M.ID_MIEMBRO
JOIN LIBROS_CRAM L ON P.ISBN = L.ISBN
JOIN BIBLIOTECAS_CRAM B ON P.ID_BIBLIOTECA = B.ID_BIBLIOTECA
WHERE P.ESTADO = 'Activo';

--(4)
--Contar cuantos libros tiene cada biblioteca en stock
--mostrando solo las que tienen mas de 5 libros distintos
SELECT B.NOMBRE_BIBLIOTECA, COUNT(LB.ISBN) AS TOTAL_TITULOS,
       SUM(LB.CANTIDAD_EN_STOCK) AS STOCK_TOTAL
FROM BIBLIOTECAS_CRAM B
JOIN LIBROS_EN_BIBLIOTECA_CRAM LB ON B.ID_BIBLIOTECA = LB.ID_BIBLIOTECA
GROUP BY B.NOMBRE_BIBLIOTECA
HAVING COUNT(LB.ISBN) > 5
ORDER BY TOTAL_TITULOS DESC;

--(5)
--Obtener el promedio de calificacion de Amazon
--por editorial mostrando solo las que superan 4.5
SELECT E.NOMBRE_EDITORIAL, 
       ROUND(AVG(L.CALIFICACION_AMAZON), 2) AS PROMEDIO_CALIFICACION
FROM EDITORIALES_CRAM E
JOIN LIBROS_CRAM L ON E.ID_EDITORIAL = L.ID_EDITORIAL
GROUP BY E.NOMBRE_EDITORIAL
HAVING AVG(L.CALIFICACION_AMAZON) > 4.5
ORDER BY PROMEDIO_CALIFICACION DESC;

--(6)
--Mostrar los miembros que tienen multas sin pagar
--con el monto total que deben
SELECT M.NOMBRE, M.APELLIDO, 
       COUNT(MU.ID_MULTA) AS TOTAL_MULTAS,
       SUM(MU.MONTO) AS MONTO_TOTAL_PENDIENTE
FROM MIEMBROS_CRAM M
JOIN MULTAS_CRAM MU ON M.ID_MIEMBRO = MU.ID_MIEMBRO
WHERE MU.PAGADA = 'N'
GROUP BY M.NOMBRE, M.APELLIDO
ORDER BY MONTO_TOTAL_PENDIENTE DESC;

--(7)
--Listar los libros que pertenecen a la categoria Fantasia
--junto con sus autores
SELECT L.TITULO, A.NOMBRE, A.APELLIDO
FROM LIBROS_CRAM L
JOIN LIBROS_POR_CATEGORIA_CRAM LC ON L.ISBN = LC.ISBN
JOIN CATEGORIAS_CRAM C ON LC.ID_CATEGORIA = C.ID_CATEGORIA
JOIN LIBROS_POR_AUTOR_CRAM LA ON L.ISBN = LA.ISBN
JOIN AUTORES_CRAM A ON LA.ID_AUTOR = A.ID_AUTOR
WHERE C.NOMBRE_CATEGORIA = 'Fantasia'
ORDER BY L.TITULO;

--(8)
--Obtener el promedio del monto de las multas
--separado entre pagadas y no pagadas
SELECT PAGADA, 
       ROUND(AVG(MONTO), 2) AS PROMEDIO_MONTO,
       COUNT(*) AS CANTIDAD
FROM MULTAS_CRAM
GROUP BY PAGADA;

--(9)
--Encontrar los miembros que han hecho
--al menos una reservacion con estado Pendiente
SELECT DISTINCT M.NOMBRE, M.APELLIDO, M.CORREO
FROM MIEMBROS_CRAM M
WHERE EXISTS (
    SELECT 1 FROM RESERVACIONES_CRAM R
    WHERE R.ID_MIEMBRO = M.ID_MIEMBRO
    AND R.ESTADO = 'Pendiente'
);

--(10)
--Listar los libros que NUNCA han sido prestados
--en ninguna biblioteca
SELECT L.TITULO, E.NOMBRE_EDITORIAL
FROM LIBROS_CRAM L
JOIN EDITORIALES_CRAM E ON L.ID_EDITORIAL = E.ID_EDITORIAL
WHERE NOT EXISTS (
    SELECT 1 FROM PRESTAMOS_CRAM P
    WHERE P.ISBN = L.ISBN
);

--(11)
--Mostrar los autores que tienen libros registrados
--en la base de datos usando subconsulta
SELECT NOMBRE, APELLIDO
FROM AUTORES_CRAM
WHERE ID_AUTOR IN (
    SELECT DISTINCT ID_AUTOR 
    FROM LIBROS_POR_AUTOR_CRAM
)
ORDER BY APELLIDO;

--(12)
--Obtener los libros cuyo precio en Amazon es menor
--que el precio promedio de todos los libros en Amazon
SELECT TITULO, PRECIO_AMAZON, ID_EDITORIAL
FROM LIBROS_CRAM
WHERE PRECIO_AMAZON < (
    SELECT AVG(PRECIO_AMAZON) FROM LIBROS_CRAM
)
ORDER BY PRECIO_AMAZON;

--(13)
--Listar los miembros que han realizado prestamos
--en mas de una biblioteca distinta
SELECT M.NOMBRE, M.APELLIDO,
       COUNT(DISTINCT P.ID_BIBLIOTECA) AS BIBLIOTECAS_VISITADAS
FROM MIEMBROS_CRAM M
JOIN PRESTAMOS_CRAM P ON M.ID_MIEMBRO = P.ID_MIEMBRO
GROUP BY M.NOMBRE, M.APELLIDO
HAVING COUNT(DISTINCT P.ID_BIBLIOTECA) > 1;

--(14)
--Mostrar los empleados junto con la biblioteca
--donde trabajan y la ciudad donde esta ubicada
SELECT E.NOMBRE, E.APELLIDO, E.PUESTO,
       B.NOMBRE_BIBLIOTECA, D.CIUDAD
FROM EMPLEADOS_CRAM E
JOIN BIBLIOTECAS_CRAM B ON E.ID_BIBLIOTECA = B.ID_BIBLIOTECA
JOIN DIRECCIONES_CRAM D ON B.ID_DIRECCION = D.ID_DIRECCION
ORDER BY B.NOMBRE_BIBLIOTECA, E.APELLIDO;

--(15)
--Obtener los libros cuya calificacion en Amazon
--es mayor que TODOS los libros de la editorial Patria Educacion
SELECT TITULO, CALIFICACION_AMAZON, ID_EDITORIAL
FROM LIBROS_CRAM
WHERE CALIFICACION_AMAZON > ALL (
    SELECT CALIFICACION_AMAZON 
    FROM LIBROS_CRAM 
    WHERE ID_EDITORIAL = (
        SELECT ID_EDITORIAL FROM EDITORIALES_CRAM
        WHERE NOMBRE_EDITORIAL = 'Patria Educacion'
    )
)
ORDER BY CALIFICACION_AMAZON DESC;

--(16)
--Listar los libros cuyo precio lista es mayor
--que el precio de ALGUN libro de la editorial Gallimard
SELECT TITULO, PRECIO_LISTA, ID_EDITORIAL
FROM LIBROS_CRAM
WHERE PRECIO_LISTA > ANY (
    SELECT PRECIO_LISTA 
    FROM LIBROS_CRAM 
    WHERE ID_EDITORIAL = (
        SELECT ID_EDITORIAL FROM EDITORIALES_CRAM
        WHERE NOMBRE_EDITORIAL = 'Gallimard'
    )
)
ORDER BY PRECIO_LISTA DESC;

--(17)
--Crear una vista que muestre los prestamos vencidos
--con datos del miembro y del libro
CREATE OR REPLACE VIEW VW_PRESTAMOS_VENCIDOS AS
SELECT P.ID_PRESTAMO, M.NOMBRE, M.APELLIDO,
       L.TITULO, P.FECHA_LIMITE, P.FECHA_DEVOLUCION,
       (P.FECHA_DEVOLUCION - P.FECHA_LIMITE) AS DIAS_RETRASO
FROM PRESTAMOS_CRAM P
JOIN MIEMBROS_CRAM M ON P.ID_MIEMBRO = M.ID_MIEMBRO
JOIN LIBROS_CRAM L ON P.ISBN = L.ISBN
WHERE P.ESTADO = 'Vencido';

--Consultar la vista creada
SELECT * FROM VW_PRESTAMOS_VENCIDOS
ORDER BY DIAS_RETRASO DESC;

--(18)
--Crear una vista que muestre el stock total de cada libro
--sumando las existencias en todas las bibliotecas
CREATE OR REPLACE VIEW VW_STOCK_TOTAL_LIBROS AS
SELECT L.ISBN, L.TITULO, 
       SUM(LB.CANTIDAD_EN_STOCK) AS STOCK_TOTAL,
       COUNT(LB.ID_BIBLIOTECA) AS EN_CUANTAS_BIBLIOTECAS
FROM LIBROS_CRAM L
JOIN LIBROS_EN_BIBLIOTECA_CRAM LB ON L.ISBN = LB.ISBN
GROUP BY L.ISBN, L.TITULO;

--Consultar la vista mostrando libros sin existencias
SELECT * FROM VW_STOCK_TOTAL_LIBROS
WHERE STOCK_TOTAL = 0;

--(19)
--Obtener los miembros que han hecho solicitudes
--pero que no tienen ningun prestamo activo (MINUS)
SELECT ID_MIEMBRO, NOMBRE, APELLIDO
FROM MIEMBROS_CRAM
WHERE ID_MIEMBRO IN (SELECT ID_MIEMBRO FROM SOLICITUDES_CRAM)
MINUS
SELECT ID_MIEMBRO, NOMBRE, APELLIDO
FROM MIEMBROS_CRAM
WHERE ID_MIEMBRO IN (
    SELECT ID_MIEMBRO FROM PRESTAMOS_CRAM WHERE ESTADO = 'Activo'
);

--(20)
--Obtener los miembros que tienen reservaciones
--y tambien tienen prestamos (INTERSECT)
SELECT ID_MIEMBRO, NOMBRE, APELLIDO
FROM MIEMBROS_CRAM
WHERE ID_MIEMBRO IN (SELECT ID_MIEMBRO FROM RESERVACIONES_CRAM)
INTERSECT
SELECT ID_MIEMBRO, NOMBRE, APELLIDO
FROM MIEMBROS_CRAM
WHERE ID_MIEMBRO IN (SELECT ID_MIEMBRO FROM PRESTAMOS_CRAM);

--(21)
--Listar todos los miembros que han tenido algun
--tipo de interaccion con la biblioteca (UNION)
SELECT ID_MIEMBRO, NOMBRE, APELLIDO, 'Prestamo' AS TIPO
FROM MIEMBROS_CRAM
WHERE ID_MIEMBRO IN (SELECT ID_MIEMBRO FROM PRESTAMOS_CRAM)
UNION
SELECT ID_MIEMBRO, NOMBRE, APELLIDO, 'Reservacion' AS TIPO
FROM MIEMBROS_CRAM
WHERE ID_MIEMBRO IN (SELECT ID_MIEMBRO FROM RESERVACIONES_CRAM)
UNION
SELECT ID_MIEMBRO, NOMBRE, APELLIDO, 'Solicitud' AS TIPO
FROM MIEMBROS_CRAM
WHERE ID_MIEMBRO IN (SELECT ID_MIEMBRO FROM SOLICITUDES_CRAM)
ORDER BY APELLIDO;

--(22)
--Usando SELF JOIN encontrar pares de miembros
--que viven en la misma ciudad
SELECT A.NOMBRE || ' ' || A.APELLIDO AS MIEMBRO_1,
       B.NOMBRE || ' ' || B.APELLIDO AS MIEMBRO_2,
       D.CIUDAD
FROM MIEMBROS_CRAM A
JOIN MIEMBROS_CRAM B ON A.ID_DIRECCION != B.ID_DIRECCION
    AND A.ID_MIEMBRO < B.ID_MIEMBRO
JOIN DIRECCIONES_CRAM D ON A.ID_DIRECCION = D.ID_DIRECCION
JOIN DIRECCIONES_CRAM D2 ON B.ID_DIRECCION = D2.ID_DIRECCION
WHERE D.CIUDAD = D2.CIUDAD
ORDER BY D.CIUDAD;

--(23)
--Usando SELF JOIN encontrar libros de la misma editorial
--que tienen calificaciones distintas
SELECT A.TITULO AS LIBRO_1, B.TITULO AS LIBRO_2,
       A.CALIFICACION_AMAZON AS CAL_1,
       B.CALIFICACION_AMAZON AS CAL_2,
       A.ID_EDITORIAL
FROM LIBROS_CRAM A
JOIN LIBROS_CRAM B ON A.ID_EDITORIAL = B.ID_EDITORIAL
    AND A.ISBN < B.ISBN
    AND A.CALIFICACION_AMAZON != B.CALIFICACION_AMAZON
ORDER BY A.ID_EDITORIAL;

--(24)
--Obtener el promedio de dias de retraso
--de los prestamos vencidos por miembro
SELECT M.NOMBRE, M.APELLIDO,
       ROUND(AVG(P.FECHA_DEVOLUCION - P.FECHA_LIMITE), 1) AS PROMEDIO_DIAS_RETRASO
FROM MIEMBROS_CRAM M
JOIN PRESTAMOS_CRAM P ON M.ID_MIEMBRO = P.ID_MIEMBRO
WHERE P.ESTADO = 'Vencido'
GROUP BY M.NOMBRE, M.APELLIDO
ORDER BY PROMEDIO_DIAS_RETRASO DESC;

--(25)
--Listar las bibliotecas que tienen libros
--con stock igual a cero
SELECT DISTINCT B.NOMBRE_BIBLIOTECA, L.TITULO,
       LB.CANTIDAD_EN_STOCK
FROM BIBLIOTECAS_CRAM B
JOIN LIBROS_EN_BIBLIOTECA_CRAM LB ON B.ID_BIBLIOTECA = LB.ID_BIBLIOTECA
JOIN LIBROS_CRAM L ON LB.ISBN = L.ISBN
WHERE LB.CANTIDAD_EN_STOCK = 0
ORDER BY B.NOMBRE_BIBLIOTECA;

--(26)
--Mostrar los autores que no tienen ningun libro
--asignado en la base de datos
SELECT A.NOMBRE, A.APELLIDO
FROM AUTORES_CRAM A
WHERE NOT EXISTS (
    SELECT 1 FROM LIBROS_POR_AUTOR_CRAM LA
    WHERE LA.ID_AUTOR = A.ID_AUTOR
);

--(27)
--Obtener el libro mas caro y el mas barato
--de cada categoria usando subconsulta
SELECT C.NOMBRE_CATEGORIA,
       MAX(L.PRECIO_LISTA) AS PRECIO_MAXIMO,
       MIN(L.PRECIO_LISTA) AS PRECIO_MINIMO,
       ROUND(AVG(L.PRECIO_LISTA), 2) AS PRECIO_PROMEDIO
FROM CATEGORIAS_CRAM C
JOIN LIBROS_POR_CATEGORIA_CRAM LC ON C.ID_CATEGORIA = LC.ID_CATEGORIA
JOIN LIBROS_CRAM L ON LC.ISBN = L.ISBN
GROUP BY C.NOMBRE_CATEGORIA
ORDER BY PRECIO_PROMEDIO DESC;

--(28)
--Listar los miembros con genero 'O' que tienen
--alguna reservacion pendiente usando EXISTS
SELECT M.NOMBRE, M.APELLIDO, M.GENERO, M.CORREO
FROM MIEMBROS_CRAM M
WHERE M.GENERO = 'O'
AND EXISTS (
    SELECT 1 FROM RESERVACIONES_CRAM R
    WHERE R.ID_MIEMBRO = M.ID_MIEMBRO
    AND R.ESTADO = 'Pendiente'
);

--(29)
--Mostrar cuantos prestamos ha realizado cada miembro
--incluyendo los que no tienen ningun prestamo
SELECT M.NOMBRE, M.APELLIDO,
       COUNT(P.ID_PRESTAMO) AS TOTAL_PRESTAMOS
FROM MIEMBROS_CRAM M
LEFT JOIN PRESTAMOS_CRAM P ON M.ID_MIEMBRO = P.ID_MIEMBRO
GROUP BY M.NOMBRE, M.APELLIDO
HAVING COUNT(P.ID_PRESTAMO) >= 0
ORDER BY TOTAL_PRESTAMOS DESC;

--(30)
--Obtener el resumen general de actividad por biblioteca:
--total de empleados, libros distintos y prestamos realizados
SELECT B.NOMBRE_BIBLIOTECA,
       COUNT(DISTINCT E.ID_EMPLEADO) AS TOTAL_EMPLEADOS,
       COUNT(DISTINCT LB.ISBN) AS TITULOS_EN_STOCK,
       COUNT(DISTINCT P.ID_PRESTAMO) AS TOTAL_PRESTAMOS
FROM BIBLIOTECAS_CRAM B
LEFT JOIN EMPLEADOS_CRAM E ON B.ID_BIBLIOTECA = E.ID_BIBLIOTECA
LEFT JOIN LIBROS_EN_BIBLIOTECA_CRAM LB ON B.ID_BIBLIOTECA = LB.ID_BIBLIOTECA
LEFT JOIN PRESTAMOS_CRAM P ON B.ID_BIBLIOTECA = P.ID_BIBLIOTECA
GROUP BY B.NOMBRE_BIBLIOTECA
ORDER BY TOTAL_PRESTAMOS DESC;