--INSERTS DE DIRECCIONES

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,11,5,'Sauceda','Guadalupe',98612,'Zacatecas','Mexico','Porton de madera, con recibidor empedrado');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,23,12,'Centro Historico','Zacatecas',98000,'Zacatecas','Mexico','Edificio colonial frente a la catedral');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,5,34,'Lomas de Chapultepec','Ciudad de Mexico',11000,'Ciudad de Mexico','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,78,'Col. Roma Norte','Ciudad de Mexico',06700,'Ciudad de Mexico','Mexico','Departamento en planta alta');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,17,9,'Zona Centro','Monterrey',64000,'Nuevo Leon','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,45,'Valle Oriente','San Pedro Garza Garcia',66260,'Nuevo Leon','Mexico','Casa esquinera con jardin');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,8,120,'Tlaquepaque','Guadalajara',44430,'Jalisco','Mexico','Local en plaza artesanal');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,67,'Zona Minerva','Guadalajara',44540,'Jalisco','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,3,15,'Centro','Puebla',72000,'Puebla','Mexico','Cerca del zocalo, portones verdes');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,230,'Angelopolis','Puebla',72830,'Puebla','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,14,88,'Doctores','Ciudad de Mexico',06720,'Ciudad de Mexico','Mexico','Planta baja, reja azul');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,5,'Col. del Valle','Ciudad de Mexico',03100,'Ciudad de Mexico','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,2,33,'Zona Rosa','Ciudad de Mexico',06600,'Ciudad de Mexico','Mexico','Oficina en piso 3');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,9,17,'Centro','Queretaro',76000,'Queretaro','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,99,'Juriquilla','Queretaro',76226,'Queretaro','Mexico','Fraccionamiento privado, caseta de seguridad');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,6,44,'Cancun Centro','Cancun',77500,'Quintana Roo','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,7,'Zona Hotelera','Cancun',77500,'Quintana Roo','Mexico','Frente al mar, acceso por lobby');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,31,56,'Col. Reforma','Tijuana',22000,'Baja California','Mexico','Casa de dos pisos, cochera doble');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,18,'Hipodromo','Tijuana',22020,'Baja California','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,4,101,'Centro','Hermosillo',83000,'Sonora','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,62,'Pitic','Hermosillo',83170,'Sonora','Mexico','Barda blanca con letrero azul');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,19,3,'Col. Centro','Chihuahua',31000,'Chihuahua','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,25,'Quintas del Sol','Chihuahua',31110,'Chihuahua','Mexico','Fraccionamiento residencial');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,7,14,'Tampico Centro','Tampico',89000,'Tamaulipas','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,77,'Col. Petrolera','Tampico',89070,'Tamaulipas','Mexico','Casa amarilla esquina');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,12,38,'Centro Historico','Morelia',58000,'Michoacan','Mexico','Cerca de la catedral, fachada de cantera');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,91,'Bosques de Morelia','Morelia',58170,'Michoacan','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,20,6,'Centro','Leon',37000,'Guanajuato','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,50,'Col. Lomas del Campestre','Leon',37150,'Guanajuato','Mexico','Casa con jardin y alberca');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,3,19,'Centro','San Luis Potosi',78000,'San Luis Potosi','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,43,'Tangamanga','San Luis Potosi',78250,'San Luis Potosi','Mexico','Cerca del parque, portón café');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,15,82,'Centro','Aguascalientes',20000,'Aguascalientes','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,11,'Jardines de la Asuncion','Aguascalientes',20270,'Aguascalientes','Mexico','Fraccionamiento cerrado');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,22,4,'Centro','Durango',34000,'Durango','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,66,'Silvestre Dorador','Durango',34070,'Durango','Mexico','Casa de ladrillo rojo');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,8,29,'Centro','Culiacan',80000,'Sinaloa','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,37,'Las Quintas','Culiacan',80060,'Sinaloa','Mexico','Residencial privado con vigilancia');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,5,73,'Centro','Mazatlan',82000,'Sinaloa','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,14,'Zona Dorada','Mazatlan',82110,'Sinaloa','Mexico','A una cuadra de la playa');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,18,55,'Centro','Tepic',63000,'Nayarit','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,28,'Mololoa','Tepic',63173,'Nayarit','Mexico','Casa blanca frente a parque');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,10,8,'Centro','Colima',28000,'Colima','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,19,'Las Vivoras','Colima',28010,'Colima','Mexico','Cerca de la Universidad de Colima');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,25,31,'Centro','Toluca',50000,'Estado de Mexico','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,47,'Valle Escondido','Atizapan',52937,'Estado de Mexico','Mexico','Condominio horizontal con alberca');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,13,60,'Centro','Cuernavaca',62000,'Morelos','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,85,'Lomas de Cortes','Cuernavaca',62240,'Morelos','Mexico','Casa con alberca y jardin amplio');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,6,22,'Centro','Oaxaca',68000,'Oaxaca','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,13,'Xochimilco','Oaxaca',68040,'Oaxaca','Mexico','Casa de adobe con patio central');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,11,41,'Centro','Tuxtla Gutierrez',29000,'Chiapas','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,53,'Col. Magisterial','Tuxtla Gutierrez',29030,'Chiapas','Mexico','Departamento en segundo piso');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,16,7,'Centro','Merida',97000,'Yucatan','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,39,'Garcia Gimenez','Merida',97070,'Yucatan','Mexico','Casa tipo colonial con hamacas');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,9,16,'Centro','Campeche',24000,'Campeche','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,27,'Col. Ana Maria Campos','Campeche',24090,'Campeche','Mexico','Edificio de 3 pisos, departamento 2B');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,4,52,'Centro','Villahermosa',86000,'Tabasco','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,64,'Atasta','Villahermosa',86100,'Tabasco','Mexico','Casa color salmon, reja negra');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,21,3,'Centro','Veracruz',91700,'Veracruz','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,86,'Boca del Rio','Veracruz',94290,'Veracruz','Mexico','Cerca del acuario, planta baja');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,7,21,'Centro','Xalapa',91000,'Veracruz','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,34,'Col. Ánimas','Xalapa',91190,'Veracruz','Mexico','Casa verde con portón de madera');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,14,9,'Centro','Acapulco',39300,'Guerrero','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,58,'Fraccionamiento Magallanes','Acapulco',39670,'Guerrero','Mexico','Vista al mar, tercer piso');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,3,76,'Centro','Chilpancingo',39000,'Guerrero','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,12,'Col. Zapata','Chilpancingo',39088,'Guerrero','Mexico','Casa de un piso, barda gris');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,10,44,'Centro','Pachuca',42000,'Hidalgo','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,23,'Col. Huazalingo','Pachuca',42083,'Hidalgo','Mexico','Condominio Villas del Lago');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,6,57,'Centro','Tlaxcala',90000,'Tlaxcala','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,31,'La Loma','Tlaxcala',90070,'Tlaxcala','Mexico','Vivienda de interes social');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,17,10,'Centro','Tepic',63000,'Nayarit','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,88,'Col. Insurgentes','Tepic',63190,'Nayarit','Mexico','Casa esquinera color beige');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,8,35,'Centro','Ciudad Juarez',32000,'Chihuahua','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,49,'Col. Partido Romero','Ciudad Juarez',32330,'Chihuahua','Mexico','Cerca de la frontera, casa de block');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,20,6,'Centro','Mexicali',21000,'Baja California','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,72,'Nueva Esperanza','Mexicali',21397,'Baja California','Mexico','Colonia obrera, casa de lamina y block');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,5,18,'Centro','La Paz',23000,'Baja California Sur','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,26,'El Centenario','La Paz',23205,'Baja California Sur','Mexico','A orillas del manglar');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,13,40,'Centro','Los Cabos',23400,'Baja California Sur','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,93,'Cabo San Lucas','Los Cabos',23453,'Baja California Sur','Mexico','Zona turistica, departamento con vista');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,2,11,'Centro','Zacatecas',98000,'Zacatecas','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,65,'Lomas de la Soledad','Zacatecas',98068,'Zacatecas','Mexico','Casa con vista a la ciudad');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,16,20,'Jerez Centro','Jerez',99300,'Zacatecas','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,42,'Col. El Refugio','Fresnillo',99010,'Zacatecas','Mexico','Casa de adobe, patio trasero grande');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,9,30,'Rio Blanco','Jerez',99301,'Zacatecas','Mexico',NULL);

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,17,'Col. Tres Cruces','Loreto',99700,'Zacatecas','Mexico','Vivienda rural con huerto');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,14,7,'Petion-Ville','Puerto Principe',NULL,'Ouest','Haiti','Barrio residencial cerca del consulado');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,33,'Centro Habana','La Habana',10200,'La Habana','Cuba','Edificio colonial, escalera interior');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,5,88,'Little Havana','Miami',33135,'Florida','Estados Unidos','Apartamento en planta baja');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,NULL,12,'Col. Escalon','San Salvador',NULL,'San Salvador','El Salvador','Casa con muro perimetral y camara');

INSERT INTO DIRECCIONES_CRAM(ID_DIRECCION,NUMERO_EDIFICIO,NUMERO_CALLE,AREA_LOCALIDAD,CIUDAD,CODIGO_POSTAL,ESTADO,PAIS,OTROS_DETALLES)
VALUES(DIR_CRAM_ID_DIR_SEQ.NEXTVAL,3,55,'Zona 10','Ciudad de Guatemala',01010,'Guatemala','Guatemala','Edificio de oficinas, piso 4');

select * from direcciones_cram;

--INSERTS DE CATEGORIAS
INSERT INTO CATEGORIAS_CRAM(ID_CATEGORIA,NOMBRE_CATEGORIA,DESCRIPCION)
VALUES(CAT_CRAM_ID_CAT_SEQ.NEXTVAL,'Ciencia Ficción', 'Libros que exploran tecnologias avanzadas, viajes por el espacio,tiempo, o una vista al futuro');

INSERT INTO CATEGORIAS_CRAM(ID_CATEGORIA,NOMBRE_CATEGORIA,DESCRIPCION)
VALUES(CAT_CRAM_ID_CAT_SEQ.NEXTVAL,'Terror','Libros diseñados para provocar miedo, suspenso y tension en el lector mediante historias de horror sobrenatural o psicologico');

INSERT INTO CATEGORIAS_CRAM(ID_CATEGORIA,NOMBRE_CATEGORIA,DESCRIPCION)
VALUES(CAT_CRAM_ID_CAT_SEQ.NEXTVAL,'Romance','Historias centradas en relaciones amorosas y sentimentales entre personajes, con finales generalmente emotivos');

INSERT INTO CATEGORIAS_CRAM(ID_CATEGORIA,NOMBRE_CATEGORIA,DESCRIPCION)
VALUES(CAT_CRAM_ID_CAT_SEQ.NEXTVAL,'Historia','Libros que narran o analizan eventos, personajes y civilizaciones del pasado de forma documentada o novelada');

INSERT INTO CATEGORIAS_CRAM(ID_CATEGORIA,NOMBRE_CATEGORIA,DESCRIPCION)
VALUES(CAT_CRAM_ID_CAT_SEQ.NEXTVAL,'Fantasia','Obras que transcurren en mundos imaginarios con magia, criaturas mitologicas y aventuras epicas');

INSERT INTO CATEGORIAS_CRAM(ID_CATEGORIA,NOMBRE_CATEGORIA,DESCRIPCION)
VALUES(CAT_CRAM_ID_CAT_SEQ.NEXTVAL,'Misterio y Thriller','Narrativas de intriga, crimenes y suspenso donde el lector descubre pistas junto al protagonista');

INSERT INTO CATEGORIAS_CRAM(ID_CATEGORIA,NOMBRE_CATEGORIA,DESCRIPCION)
VALUES(CAT_CRAM_ID_CAT_SEQ.NEXTVAL,'Autoayuda',NULL);

INSERT INTO CATEGORIAS_CRAM(ID_CATEGORIA,NOMBRE_CATEGORIA,DESCRIPCION)
VALUES(CAT_CRAM_ID_CAT_SEQ.NEXTVAL,'Biografia',NULL);

INSERT INTO CATEGORIAS_CRAM(ID_CATEGORIA,NOMBRE_CATEGORIA,DESCRIPCION)
VALUES(CAT_CRAM_ID_CAT_SEQ.NEXTVAL,'Infantil y Juvenil','Libros pensados para ninos y jovenes con lenguaje accesible, ilustraciones y temas formativos o de aventura');

INSERT INTO CATEGORIAS_CRAM(ID_CATEGORIA,NOMBRE_CATEGORIA,DESCRIPCION)
VALUES(CAT_CRAM_ID_CAT_SEQ.NEXTVAL,'Poesia',NULL);

select * from categorias_cram;

--INSERTS DE EDITORIALES
INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Penguin Random House','United Kingdom','www.penguinbooks.com');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Fondo de Cultura Economica','Mexico','www.fondodeculturaeconomica.com');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Planeta','España','www.planeta.es');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Del Rey Books','Estados Unidos','www.delreybooks.com');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'HarperCollins','Estados Unidos','www.harpercollins.com');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Simon and Schuster','Estados Unidos','www.simonandschuster.com');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Alfaguara','España','www.alfaguara.com');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Anagrama','España','www.anagrama-ed.es');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Patria Educacion','Mexico',NULL);

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Santillana','Mexico','www.santillana.com.mx');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Macmillan Publishers','Reino Unido','www.macmillan.com');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Gallimard','Francia','www.gallimard.fr');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Scholastic','Estados Unidos','www.scholastic.com');

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Ediciones Era','Mexico',NULL);

INSERT INTO EDITORIALES_CRAM(ID_EDITORIAL,NOMBRE_EDITORIAL,PAIS,SITIO_WEB)
VALUES(EDIT_CRAM_ID_EDIT_SEQ.NEXTVAL,'Tusquets Editores','España','www.tusquetseditores.com');

select * from editoriales_cram;

--INSERTS DE AUTORES

--Bantam Books
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Dan','Simmons');

-- Penguin Random House
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Stephen','King');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Toni','Morrison');

-- Del Rey Books
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'George R.R.','Martin');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Brandon','Sanderson');

-- HarperCollins
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'C.S.','Lewis');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Neil','Gaiman');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Agatha','Christie');

-- Simon and Schuster
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Ernest','Hemingway');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Stephen','Hawking');

-- Alfaguara
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Gabriel','Garcia Marquez');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Mario','Vargas Llosa');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Isabel','Allende');

-- Anagrama
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Charles','Bukowski');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Roberto','Bolano');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Paul','Auster');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Javier','Marias');

-- Fondo de Cultura Economica
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Fiodor','Dostoievski');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Octavio','Paz');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Juan','Rulfo');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Leon','Tolstoi');

-- Planeta
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Ken','Follett');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Carlos','Ruiz Zafon');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Dan','Brown');

-- Santillana
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Laura','Esquivel');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Jorge','Amado');

-- Macmillan Publishers
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'John','Steinbeck');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Rudyard','Kipling');

-- Gallimard
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Albert','Camus');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Jean-Paul','Sartre');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Marcel','Proust');

-- Scholastic
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'J.K.','Rowling');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'R.L.','Stine');

-- Ediciones Era
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Elena','Poniatowska');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Carlos','Monsivais');

-- Tusquets Editores
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Milan','Kundera');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Jorge','Semprun');

-- Patria Educacion
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Erich','Fromm');

-- Adicionales
INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Franz','Kafka');

INSERT INTO AUTORES_CRAM(ID_AUTOR,NOMBRE,APELLIDO)
VALUES(AUT_CRAM_ID_AUT_SEQ.NEXTVAL,'Haruki','Murakami');

select * from autores_cram;
select * from direcciones_cram;--id-91-180
--INSERTS DE MIEMBROS
INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,91,'M','Gabriel','Bortoleto','4933271156','BortoSexo@gmail.com','Cabello y ojos marrones, tez morena, habla portugues');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,92,'F','Maria','Gonzalez','4921345678','maria.gonzalez@gmail.com','Cabello negro, ojos cafes, usa lentes');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,93,'M','Carlos','Ramirez','5512349876','carlos.ramirez@hotmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,94,'F','Sofia','Lopez','8112345432','sofia.lopez@outlook.com','Estudiante universitaria, carrera de derecho');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,95,'M','Luis','Martinez','3312987654','luis.mtz@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,96,'F','Ana','Hernandez','4921567890','ana.hdz@gmail.com','Profesora de primaria, visita la biblioteca los sabados');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,97,'M','Jorge','Perez','6671234567','jorge.perez@yahoo.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,98,'F','Valentina','Torres',NULL,'vale.torres@gmail.com','Escritora aficionada, interes en literatura latinoamericana');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,99,'M','Roberto','Flores','8183456789','roberto.flores@hotmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,100,'F','Daniela','Cruz','4491234567','dani.cruz@gmail.com','Medico general, lee en sus tiempos libres');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,101,'M','Miguel','Morales',NULL,NULL,'Adulto mayor, prefiere libros de historia');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,102,'F','Paola','Jimenez','5512876543','paola.jimenez@outlook.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,103,'M','Eduardo','Diaz','3312456789','edu.diaz@gmail.com','Ingeniero en sistemas, fan de la ciencia ficcion');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,104,'F','Gabriela','Reyes',NULL,'gaby.reyes@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,105,'M','Fernando','Gutierrez','4921098765','fer.gutierrez@hotmail.com','Abogado, interes en biografia y ensayo');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,106,'O','Alex','Vargas','9981234567','alex.vargas@gmail.com','Prefiere que le llamen Alex, estudiante de artes');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,107,'F','Carmen','Romero','6641357924','carmen.romero@yahoo.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,108,'M','Hector','Medina','6141234567','hector.medina@gmail.com','Trabaja en turismo, lee guias de viaje');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,109,'F','Lucia','Aguilar',NULL,'lucia.aguilar@outlook.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,110,'M','Ricardo','Castillo','8991234567','ricardo.castillo@gmail.com','Contador, lector habitual de novela negra');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,111,'F','Natalia','Mendoza','3221456789','naty.mendoza@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,112,'M','Alejandro','Ruiz','7221234567','alex.ruiz@hotmail.com','Arquitecto, interes en arte y diseno');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,113,'F','Mariana','Ortiz',NULL,NULL,'Sin telefono ni correo registrado');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,114,'M','Ivan','Delgado','8341234567','ivan.delgado@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,115,'F','Veronica','Guerrero','4481234567','vero.guerrero@yahoo.com','Psicologa, interes en autoayuda y filosofia');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,116,'M','Pablo','Nunez','6861234567','pablo.nunez@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,117,'O','Jordan','Soto','9141234567','jordan.soto@outlook.com','No binario, estudiante de filosofia');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,118,'F','Diana','Cervantes',NULL,'diana.cervantes@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,119,'M','Andres','Sandoval','9611234567','andres.sandoval@hotmail.com','Veterinario, fan de la literatura japonesa');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,120,'F','Claudia','Vega','7121234567','claudia.vega@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,121,'M','Oscar','Rios','6691234567','oscar.rios@gmail.com','Musico, lee sobre historia del arte');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,122,'F','Monica','Fuentes',NULL,'monica.fuentes@outlook.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,123,'M','Sergio','Contreras','9381234567','sergio.contreras@gmail.com','Chef, interes en gastronomia y cultura');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,124,'F','Adriana','Lara','9121234567','adriana.lara@yahoo.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,125,'M','Diego','Espinoza','7521234567','diego.espinoza@gmail.com','Estudiante de medicina, poco tiempo libre');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,126,'F','Patricia','Mendez',NULL,NULL,'Ama de casa, prefiere novela romantica');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,127,'M','Manuel','Rojas','8661234567','manuel.rojas@hotmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,128,'F','Alejandra','Navarro','7411234567','ale.navarro@gmail.com','Maestra de secundaria, promotora de lectura');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,129,'M','Francisco','Herrera',NULL,'fco.herrera@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,130,'O','Sam','Ibarra','5541234567','sam.ibarra@outlook.com','Diseñador grafico, lee sobre tipografia y arte');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,131,'F','Rosa','Dominguez','9511234567','rosa.dominguez@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,132,'M','Arturo','Campos','4341234567','arturo.campos@yahoo.com','Piloto, lector de thriller y aventura');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,133,'F','Irene','Pacheco',NULL,'irene.pacheco@hotmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,134,'M','Raul','Leon','8441234567','raul.leon@gmail.com','Economista, interes en ensayo politico');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,135,'F','Silvia','Castro',NULL,NULL,'Sin datos de contacto registrados');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,136,'M','Ernesto','Vidal','9221234567','ernesto.vidal@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,137,'F','Beatriz','Montes','7771234567','bea.montes@outlook.com','Bibliotecaria en otra sucursal, miembro honoraria');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,138,'M','Victor','Iglesias','6181234567','victor.iglesias@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,139,'F','Lorena','Pena','8121234567','lorena.pena@yahoo.com','Fotografa, interes en arte y poesia');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,140,'M','Guillermo','Acosta',NULL,'guillermo.acosta@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,141,'F','Esperanza','Salinas','9171234567','espe.salinas@hotmail.com','Abuela de 3 nietos, lee cuentos infantiles');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,142,'M','Jonatan','Mejia','7191234567','jonatan.mejia@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,143,'F','Yesenia','Trejo',NULL,'yesenia.trejo@outlook.com','Nutriologa, interes en ciencia y salud');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,144,'M','Bernardo','Fuentes','6241234567','bernardo.fuentes@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,145,'F','Nadia','Esquivel','3381234567','nadia.esquivel@gmail.com','Bailarina, lee sobre danza y teatro');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,146,'M','Cristian','Olvera',NULL,NULL,'Joven de 16 anos, lector de manga y fantasia');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,147,'F','Miriam','Alvarado','9521234567','miriam.alvarado@yahoo.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,148,'M','Tomas','Barrera','8711234567','tomas.barrera@gmail.com','Jubilado, visita la biblioteca diariamente');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,149,'F','Ivonne','Tapia',NULL,'ivonne.tapia@hotmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,150,'O','Robin','Estrada','5591234567','robin.estrada@gmail.com','Activista, interes en sociologia y politica');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,151,'M','Alvaro','Ponce','4711234567','alvaro.ponce@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,152,'F','Rebeca','Solis','7231234567','rebeca.solis@outlook.com','Historiadora, especialista en epoca colonial');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,153,'M','Ignacio','Quintero',NULL,'ignacio.quintero@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,154,'F','Karla','Bustos','9811234567','karla.bustos@gmail.com','Periodista, lectora voraz de no ficcion');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,155,'M','Enrique','Maldonado','6471234567','enrique.maldonado@yahoo.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,156,'F','Susana','Carrillo',NULL,'susana.carrillo@gmail.com','Trabaja en ONG, interes en derechos humanos');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,157,'M','Leandro','Avila','9951234567','leandro.avila@hotmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,158,'F','Perla','Zuniga','7321234567','perla.zuniga@gmail.com','Estudiante de letras hispanicas');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,159,'M','Rogelio','Macias',NULL,NULL,'Sin datos de contacto, prefiere anonimato');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,160,'F','Wendy','Palacios','9641234567','wendy.palacios@outlook.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,161,'M','Octavio','Cisneros','7431234567','octavio.cisneros@gmail.com','Filosofo aficionado, coleccionista de libros antiguos');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,162,'F','Alicia','Bravo',NULL,'alicia.bravo@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,163,'M','Gerardo','Ibañez','8881234567','gerardo.ibanez@hotmail.com','Deportista, lee sobre nutricion y rendimiento');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,164,'F','Fabiola','Cano','3121234567','fabiola.cano@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,165,'M','Horacio','Salas',NULL,'horacio.salas@yahoo.com','Escritor independiente, miembro frecuente');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,166,'F','Esther','Quiroz','9291234567','esther.quiroz@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,167,'M','Cesar','Monroy','4621234567','cesar.monroy@outlook.com','Docente universitario de literatura');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,168,'F','Jacqueline','Lozano',NULL,NULL,'Miembro desde hace 10 anos, sin contacto actualizado');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,169,'M','Isidro','Velazquez','9341234567','isidro.velazquez@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,170,'F','Norma','Acevedo','7541234567','norma.acevedo@gmail.com','Enfermera, lee en turnos nocturnos');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,171,'M','Benjamin','Esteves',NULL,'benjamin.esteves@hotmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,172,'F','Graciela','Paredes','9711234567','graciela.paredes@gmail.com','Pintora, se inspira en novelas para sus obras');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,173,'M','Aurelio','Venegas','6351234567','aurelio.venegas@yahoo.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,174,'F','Consuelo','Rangel',NULL,'consuelo.rangel@gmail.com','Traductora, domina frances e ingles');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,175,'M','Mauricio','Alonzo','8141234567','mauricio.alonzo@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,176,'F','Araceli','Duran',NULL,NULL,'Adulta mayor, miembro fundadora de la biblioteca');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,177,'M','Genaro','Villanueva','9841234567','genaro.villanueva@outlook.com','Programador, fan de ciencia ficcion y cyberpunk');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,178,'F','Rocio','Taboada',NULL,'rocio.taboada@gmail.com',NULL);

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,179,'M','Abelardo','Fuentes','7671234567','abelardo.fuentes@hotmail.com','Historiador local, investiga sobre Zacatecas');

INSERT INTO MIEMBROS_CRAM(ID_MIEMBRO,ID_DIRECCION,GENERO,NOMBRE,APELLIDO,TELEFONO,CORREO,OTROS_DETALLES)
VALUES(MIE_CRAM_ID_MIE_SEQ.NEXTVAL,180,'F','Dolores','Marquez',NULL,'dolores.marquez@gmail.com','Jubilada, lectora de romance y novela historica');
COMMIT;

select * from BIBLIOTECAS_cram;

--INSERTS DE BIBLIOTECAS
INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,91,'Mauricio Magdaleno','Fachada color blanco, edificio cilindrico con ventanas');

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,95,'Jose Vasconcelos','Biblioteca moderna con jardines interiores y sala de lectura digital');

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,121,'Francisco Garcia Salinas',NULL);

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,118,'Biblioteca Daniel Cosio Villegas','Especializada en ciencias sociales, pertenece al Tec de Monterrey');

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,125,'Juan Jose Arreola','Edificio de dos pisos con auditorio para eventos literarios');

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,133,'Biblioteca Publica de Guadalajara',NULL);

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,141,'Sor Juana Ines de la Cruz','Biblioteca especializada en literatura mexicana, fachada colonial restaurada');

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,150,'Octavio Paz','Cuenta con sala infantil, sala de computo y terraza de lectura al aire libre');

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,158,'Biblioteca Central UNAM',NULL);

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,167,'Biblioteca Publica del Estado de Jalisco','Edificio historico en el centro de Guadalajara, coleccion de mapas antiguos');

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,175,'Carlos Monsivais',NULL);

INSERT INTO BIBLIOTECAS_CRAM(ID_BIBLIOTECA,ID_DIRECCION,NOMBRE_BIBLIOTECA,DETALLES)
VALUES(BIB_CRAM_ID_BIB_SEQ.NEXTVAL,173,'Biblioteca de Mexico Jose Vasconcelos','Sede principal ubicada en la Ciudad de Mexico, mas de 100 anos de historia');

select * from bibliotecas_cram;

--INSERTS DE EMPLEADOS
INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,26,'Pedro','Ramirez','Conserje','15/05/2007','peramirez@gmail.com');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,26,'Laura','Sandoval','Bibliotecaria Jefe','12/03/2010','laura.sandoval@biblioMM.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,26,'Carlos','Espinoza','Catalogador','08/06/2015',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,26,'Miriam','Tapia','Auxiliar de Servicios','20/01/2019','miriam.tapia@biblioMM.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,27,'Ricardo','Fuentes','Director','03/09/2008','ricardo.fuentes@vasconcelos.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,27,'Sofia','Herrera','Bibliotecaria','14/02/2012','sofia.herrera@vasconcelos.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,27,'Andres','Mora','Tecnico en Sistemas','27/07/2017',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,27,'Diana','Castellanos','Promotora Cultural','05/11/2020','diana.castellanos@vasconcelos.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,27,'Jesus','Palacios','Conserje','18/04/2021',NULL);

-- BIBLIOTECA 3 - Francisco Garcia Salinas (3 empleados)
INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,28,'Elena','Rios','Bibliotecaria Jefe','22/08/2009','elena.rios@fgs.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,28,'Marco','Villanueva','Auxiliar de Servicios','10/03/2016',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,28,'Gabriela','Soto','Catalogadora','30/09/2018','gabriela.soto@fgs.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,28,'Hector','Montes','Director','15/01/2006','hector.montes@cosiovillegas.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,29,'Patricia','Guzman','Investigadora','28/05/2013','patricia.guzman@cosiovillegas.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,29,'Ivan','Salazar','Auxiliar de Archivo','11/10/2017',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,29,'Fernanda','Quiroz','Bibliotecaria','07/03/2021','fernanda.quiroz@cosiovillegas.mx');


INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,30,'Alejandro','Ramos','Bibliotecario Jefe','19/06/2011','alejandro.ramos@arreola.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,30,'Claudia','Ibarra','Promotora Cultural','24/02/2018',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,30,'Roberto','Acuna','Conserje','13/08/2022','roberto.acuna@arreola.mx');


INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,31,'Veronica','Padilla','Directora','02/04/2005','veronica.padilla@bpguadalajara.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,31,'Manuel','Cervantes','Bibliotecario','17/09/2010','manuel.cervantes@bpguadalajara.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,31,'Yolanda','Peña','Catalogadora','06/01/2014',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,31,'Luis','Alvarado','Tecnico en Sistemas','23/07/2019','luis.alvarado@bpguadalajara.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,31,'Natalia','Olvera','Auxiliar de Servicios','09/03/2023',NULL);


INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,32,'Beatriz','Contreras','Directora','14/11/2007','beatriz.contreras@sorjuana.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,32,'Jorge','Medina','Investigador Literario','25/05/2013','jorge.medina@sorjuana.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,32,'Paulina','Estrada','Bibliotecaria','18/02/2017',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,32,'Tomas','Guerrero','Conserje','30/10/2021','tomas.guerrero@sorjuana.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,33,'Ernesto','Vargas','Bibliotecario Jefe','08/07/2009','ernesto.vargas@octaviopaz.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,33,'Adriana','Reyes','Promotora Cultural','21/04/2015',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,33,'Samuel','Dominguez','Auxiliar de Servicios','12/09/2020','samuel.dominguez@octaviopaz.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,34,'Guillermo','Navarrete','Director','01/02/2004','guillermo.navarrete@unam.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,34,'Monica','Lara','Bibliotecaria Senior','16/08/2009','monica.lara@unam.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,34,'Eduardo','Campos','Catalogador','04/03/2014',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,34,'Karla','Nunez','Tecnica en Digitalizacion','29/06/2018','karla.nunez@unam.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,34,'Diego','Aguilar','Auxiliar de Servicios','15/01/2023',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,34,'Rosa','Mendivil','Directora','10/05/2006','rosa.mendivil@bpjalisco.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,34,'Armando','Cisneros','Archivista Historico','22/11/2011','armando.cisneros@bpjalisco.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,34,'Leticia','Bustos','Bibliotecaria','07/08/2016',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,34,'Omar','Trejo','Conserje','03/02/2022','omar.trejo@bpjalisco.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,35,'Alejandra','Fuentes','Bibliotecaria Jefe','19/03/2013','alejandra.fuentes@monsivais.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,35,'Rodrigo','Solis','Auxiliar de Servicios','14/07/2018',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,35,'Ivonne','Maldonado','Promotora Cultural','28/01/2022','ivonne.maldonado@monsivais.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,36,'Francisco','Moreno','Director General','05/06/2002','francisco.moreno@bibliomex.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,36,'Silvia','Aragon','Coordinadora Academica','17/09/2008','silvia.aragon@bibliomex.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,36,'Pablo','Zuniga','Catalogador Senior','08/04/2013',NULL);

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,36,'Mariana','Velasco','Tecnica en Restauracion','23/10/2018','mariana.velasco@bibliomex.mx');

INSERT INTO EMPLEADOS_CRAM(ID_EMPLEADO,ID_BIBLIOTECA,NOMBRE,APELLIDO,PUESTO,FECHA_CONTRATACION,CORREO)
VALUES(EMP_CRAM_ID_EMP_SEQ.NEXTVAL,36,'Kevin','Delgado','Auxiliar de Servicios','11/05/2023',NULL);
select * from LIBROS_cram;
SELECT * FROM EDITORIALES_CRAM;
--INSERTS DE LIBROS
INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780553283686,'HYPERION','26/05/1989',16,200,176,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780385333849,'El Nombre de la Rosa','05/10/1980',16,320,275,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780385490818,'El Pendulo de Foucault','15/11/1988',16,350,299,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780307474728,'Cien Anos de Soledad','05/06/1967',16,280,240,4.9);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780679720201,'En el Camino','05/09/1957',16,220,185,4.3);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780385542364,'La Insoportable Levedad del Ser','12/04/1984',16,260,210,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780307350441,'2666','15/11/2004',16,420,370,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9789681604974,'El Laberinto de la Soledad','01/03/1950',17,180,150,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9789681619831,'Pedro Paramo','19/03/1955',17,160,130,4.9);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9789681605063,'Crimen y Castigo','01/01/1866',17,240,195,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9789681637422,'Guerra y Paz','01/01/1869',17,450,380,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9789681648391,'Los Hermanos Karamazov','01/11/1880',17,380,320,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9789681659234,'El Llano en Llamas','15/08/1953',17,150,120,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9789681671823,'Anna Karenina','01/03/1878',17,390,330,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788408113331,'Los Pilares de la Tierra','05/10/1989',18,480,410,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788408124578,'El Codigo Da Vinci','18/03/2003',18,290,240,4.2);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788408135692,'La Sombra del Viento','01/04/2001',18,310,260,4.9);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788408146803,'Un Mundo sin Fin','04/10/2007',18,520,440,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788408157914,'Inferno','14/05/2013',18,280,230,4.1);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780061996129,'El Leon la Bruja y el Ropero','16/10/1950',19,210,175,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780062073488,'Good Omens','01/05/1990',19,270,225,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780062409850,'Asesinato en el Orient Express','01/01/1934',19,230,190,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780062420244,'Diez Negritos','06/11/1939',19,220,180,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780062431035,'El Hobbit','21/09/1937',19,260,215,4.9);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780062442126,'Stardust','01/10/1999',19,240,200,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780743273565,'El Gran Gatsby','10/04/1925',19,190,155,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780743297332,'Por Quien Doblan las Campanas','21/10/1940',20,250,210,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780743311342,'El Viejo y el Mar','08/09/1952',20,180,145,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780743325356,'Historia Breve del Tiempo','01/04/1988',20,290,245,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780743339370,'El Universo en una Cascara de Nuez','09/10/2001',20,270,225,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788420471839,'La Fiesta del Chivo','01/03/2000',21,310,265,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788420482842,'Conversacion en la Catedral','01/10/1969',21,340,290,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788420493853,'La Casa de los Espiritus','01/10/1982',21,295,250,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788420504864,'Eva Luna','01/10/1987',21,270,225,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788420515875,'El Coronel no tiene quien le Escriba','01/01/1961',21,195,160,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788420526886,'Cronica de una Muerte Anunciada','01/04/1981',21,210,175,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788433914521,'Factotum','01/01/1975',22,230,190,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788433925534,'La Ciudad y los Perros','01/10/1963',22,280,235,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788433936547,'El Palacio de la Luna','01/09/1990',22,265,220,4.4);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788433947558,'Los Detectives Salvajes','01/10/1998',22,320,275,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788433958561,'Mujeres','15/02/1978',22,215,180,4.3);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788433969574,'Hombres sin Mujeres','01/04/2014',22,250,210,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786074382341,'El Arte de Amar','01/01/1956',23,195,160,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786074393354,'Miedo a la Libertad','01/01/1941',23,220,185,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786074404367,'Tener o Ser','01/01/1976',23,210,175,4.4);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786074415370,'Introduccion a las Matematicas','15/08/2010',23,380,320,4.2);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786074426383,'Fundamentos de Fisica','20/01/2015',23,420,355,4.3);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786070106392,'Como Agua para Chocolate','01/09/1989',24,230,195,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786070117405,'La Ley del Amor','01/10/1995',24,215,180,4.3);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786070128418,'Gabriela Clavo y Canela','01/01/1958',24,240,200,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786070139421,'Dona Flor y sus dos Maridos','01/01/1966',24,255,215,4.4);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786070140434,'Gramatica de la Lengua Espanola','10/03/2018',24,350,295,4.1);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780333761021,'Las Uvas de la Ira','14/04/1939',25,270,225,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780333772034,'De Ratones y Hombres','25/02/1937',25,210,175,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780333783047,'El Libro de la Selva','01/01/1894',25,190,155,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780333794050,'Kim','01/01/1901',25,200,165,4.4);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780333805063,'Al Este del Eden','19/09/1952',25,290,245,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780333816076,'La Perla','30/11/1947',25,180,145,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9782070360024,'El Extranjero','01/06/1942',26,185,150,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9782070371037,'La Nausea','01/04/1938',26,195,160,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9782070382040,'La Peste','01/06/1947',26,210,175,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9782070393053,'En Busca del Tiempo Perdido','14/11/1913',26,550,470,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9782070404066,'El Muro','01/01/1939',26,190,155,4.4);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780439708180,'Harry Potter y la Piedra Filosofal','26/06/1997',27,280,235,4.9);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780439708197,'Harry Potter y la Camara Secreta','02/07/1998',27,280,235,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780439708203,'Harry Potter y el Prisionero de Azkaban','08/07/1999',27,290,245,4.9);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780439708210,'La Casa del Terror','01/07/1992',27,195,160,4.3);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780439708227,'Pesadillas','01/07/1992',27,185,150,4.2);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780439708234,'El Monstruo de la Laguna','01/04/1993',27,185,150,4.1);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786074500134,'La Noche de Tlatelolco','02/10/1971',28,220,185,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786074511147,'Hasta no Verte Jesus Mio','01/01/1969',28,210,175,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786074522150,'Dias de Guardar','01/01/1970',28,195,160,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786074533163,'El Principio del Placer','01/01/1972',28,200,165,4.4);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9786074544176,'Parte de Guerra','02/10/1999',28,230,195,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788483103821,'La Broma','01/01/1967',29,240,200,4.6);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788483114834,'El Libro de la Risa y el Olvido','01/01/1979',29,255,215,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788483125847,'La Autobiografia de Federico Sanchez','01/01/1977',29,230,190,4.4);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788483136850,'La Inmortalidad','01/01/1990',29,265,220,4.5);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9788483147863,'La Lentitud','01/01/1995',29,220,185,4.3);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780345339706,'Juego de Tronos','01/08/1996',30,380,320,4.9);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780345350978,'El Camino de los Reyes','31/08/2010',30,420,360,4.9);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780345362001,'Elantris','21/04/2005',30,310,265,4.7);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780345373014,'El Imperio Final','17/07/2006',30,350,295,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780345384027,'Choque de Reyes','16/11/1998',30,390,330,4.8);

INSERT INTO LIBROS_CRAM(ISBN,TITULO,FECHA_PUBLICACION,ID_EDITORIAL,PRECIO_LISTA,PRECIO_AMAZON,CALIFICACION_AMAZON)
VALUES(9780345395030,'Tormenta de Espadas','08/08/2000',30,400,340,4.9);

SELECT * FROM AUTORES_CRAM;
SELECT * FROM LIBROS_CRAM;
SELECT * FROM LIBROS_POR_AUTOR;
COMMIT;
--INSERTS LIBROS POR AUTOR

-- ID 41 -Dan Simmons
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN)
VALUES(41,9780553283686);

-- ID 42 - Stephen King
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(42,9780439708210);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(42,9780439708227);

-- ID 43 - Toni Morrison (sin libros asignados)

-- ID 44 - George R.R. Martin
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(44,9780345339706);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(44,9780345384027);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(44,9780345395030);

-- ID 45 - Brandon Sanderson
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(45,9780345350978);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(45,9780345362001);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(45,9780345373014);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(45,9780345384027);

-- ID 46 - C.S. Lewis
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(46,9780062431035);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(46,9780061996129);

-- ID 47 - Neil Gaiman
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(47,9780062073488);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(47,9780062442126);

-- ID 48 - Agatha Christie
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(48,9780062409850);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(48,9780062420244);

-- ID 49 - Ernest Hemingway
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(49,9780743297332);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(49,9780743311342);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(49,9780743273565);

-- ID 50 - Stephen Hawking
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(50,9780743325356);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(50,9780743339370);

-- ID 51 - Gabriel Garcia Marquez
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(51,9780307474728);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(51,9788420515875);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(51,9788420526886);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(51,9788420482842);

-- ID 52 - Mario Vargas Llosa
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(52,9788420471839);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(52,9788433925534);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(52,9788420482842);

-- ID 53 - Isabel Allende
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(53,9788420493853);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(53,9788420504864);

-- ID 54 - Charles Bukowski
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(54,9788433914521);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(54,9788433958561);

-- ID 55 - Roberto Bolano
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(55,9780307350441);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(55,9788433947558);

-- ID 56 - Paul Auster (sin libros asignados)

-- ID 57 - Javier Marias (sin libros asignados)

-- ID 58 - Fiodor Dostoievski
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(58,9789681605063);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(58,9789681648391);

-- ID 59 - Octavio Paz
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(59,9789681604974);

-- ID 60 - Juan Rulfo
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(60,9789681619831);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(60,9789681659234);

-- ID 61 - Leon Tolstoi
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(61,9789681637422);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(61,9789681671823);

-- ID 62 - Ken Follett
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(62,9788408113331);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(62,9788408146803);

-- ID 63 - Carlos Ruiz Zafon
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(63,9788408135692);

-- ID 64 - Dan Brown
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(64,9788408124578);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(64,9788408157914);

-- ID 65 - Laura Esquivel
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(65,9786070106392);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(65,9786070117405);

-- ID 66 - Jorge Amado
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(66,9786070128418);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(66,9786070139421);

-- ID 67 - John Steinbeck
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(67,9780333761021);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(67,9780333772034);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(67,9780333805063);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(67,9780333816076);

-- ID 68 - Rudyard Kipling
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(68,9780333783047);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(68,9780333794050);

-- ID 69 - Albert Camus
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(69,9782070360024);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(69,9782070382040);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(69,9782070404066);

-- ID 70 - Jean-Paul Sartre
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(70,9782070371037);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(70,9782070404066);

-- ID 71 - Marcel Proust
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(71,9782070393053);

-- ID 72 - J.K. Rowling
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(72,9780439708180);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(72,9780439708197);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(72,9780439708203);

-- ID 73 - R.L. Stine (sin libros asignados)

-- ID 74 - Elena Poniatowska
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(74,9786074500134);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(74,9786074511147);

-- ID 75 - Carlos Monsivais
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(75,9786074522150);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(75,9786074533163);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(75,9786074544176);

-- ID 76 - Milan Kundera
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(76,9788483103821);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(76,9788483114834);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(76,9788483136850);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(76,9788483147863);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(76,9780385542364);

-- ID 77 - Jorge Semprun
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(77,9788483125847);

-- ID 78 - Erich Fromm
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(78,9786074382341);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(78,9786074393354);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(78,9786074404367);

-- ID 79 - Franz Kafka
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(79,9780385333849);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(79,9780385490818);

-- ID 80 - Haruki Murakami
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(80,9788433936547);
INSERT INTO LIBROS_POR_AUTOR_CRAM(ID_AUTOR,ISBN) VALUES(80,9788433969574);
select * from libros_por_autor_cram;
