

-- -------------------------------------------------------
-- TABLAS SIN FK (tablas padre)
-- -------------------------------------------------------
--TABLA DIRECCIONES-[*]
CREATE TABLE DIRECCIONES_CRAM(
    ID_DIRECCION NUMBER(6) CONSTRAINT DIR_CRAM_PK PRIMARY KEY,
    NUMERO_EDIFICIO NUMBER(5),
    NUMERO_CALLE NUMBER(5) CONSTRAINT DIR_CRAM_NUM_CAL_NN NOT NULL,
    AREA_LOCALIDAD VARCHAR2(100),
    CIUDAD VARCHAR2(50) CONSTRAINT DIR_CRAM_CIU_NN NOT NULL,
    CODIGO_POSTAL NUMBER(6),
    ESTADO VARCHAR2(50),
    PAIS VARCHAR2(50) CONSTRAINT DIR_CRAM_PAI_NN NOT NULL,
    OTROS_DETALLES VARCHAR2(150)
);

--TABLA CATEGORIAS-[*]
CREATE TABLE CATEGORIAS_CRAM(
    ID_CATEGORIA NUMBER(6) CONSTRAINT CAT_CRAM_PK PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR2(40),
    DESCRIPCION VARCHAR2(200)
);

--TABLA EDITORIALES-[*]
CREATE TABLE EDITORIALES_CRAM(
    ID_EDITORIAL NUMBER(6) CONSTRAINT EDIT_CRAM_PK PRIMARY KEY,
    NOMBRE_EDITORIAL VARCHAR2(50) CONSTRAINT EDIT_CRAM_NOM_NN NOT NULL,
    PAIS VARCHAR2(40),
    SITIO_WEB VARCHAR2(150)
);

--TABLA AUTORES-[*]
CREATE TABLE AUTORES_CRAM(
    ID_AUTOR NUMBER(6) CONSTRAINT AUT_CRAM_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50) CONSTRAINT AUT_CRAM_NOM_NN NOT NULL,
    APELLIDO VARCHAR2(50) CONSTRAINT AUT_CRAM_APE_NN NOT NULL
);

-----ACA VOY---
-- -------------------------------------------------------
-- TABLAS CON FK (tablas dependientes)
-- -------------------------------------------------------

--TABLA MIEMBROS-[*]
CREATE TABLE MIEMBROS_CRAM(
    ID_MIEMBRO NUMBER(6) CONSTRAINT MIE_CRAM_PK PRIMARY KEY,
    ID_DIRECCION NUMBER(6) CONSTRAINT MIE_CRAM_DIR_NN NOT NULL,
    GENERO CHAR(1) CONSTRAINT MIE_CRAM_GEN_CK CHECK (GENERO IN ('M','F')),
    NOMBRE VARCHAR2(40) CONSTRAINT MIE_CRAM_NOM_NN NOT NULL,
    APELLIDO VARCHAR2(40) CONSTRAINT MIE_CRAM_APE_NN NOT NULL,
    TELEFONO CHAR(10),
    CORREO VARCHAR2(60) CONSTRAINT MIE_CRAM_COR_UK UNIQUE,
    OTROS_DETALLES VARCHAR2(150),
    CONSTRAINT DIR_CRAM_MIE_CRAM_FK FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES_CRAM(ID_DIRECCION)
);

--TABLA BIBLIOTECAS-[*]
CREATE TABLE BIBLIOTECAS_CRAM(
    ID_BIBLIOTECA NUMBER(6) CONSTRAINT BIB_CRAM_PK PRIMARY KEY,
    ID_DIRECCION NUMBER(6) CONSTRAINT BIB_CRAM_DIR_NN NOT NULL,
    NOMBRE_BIBLIOTECA VARCHAR2(50) CONSTRAINT BIB_CRAM_NOM_NN NOT NULL,
    DETALLES VARCHAR2(150),
    CONSTRAINT DIR_CRAM_BIB_CRAM_FK FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCIONES_CRAM(ID_DIRECCION)
);

--TABLA EMPLEADOS--[*]
CREATE TABLE EMPLEADOS_CRAM(
    ID_EMPLEADO NUMBER(6) CONSTRAINT EMP_CRAM_PK PRIMARY KEY,
    ID_BIBLIOTECA NUMBER(6) CONSTRAINT EMP_CRAM_BIB_NN NOT NULL,
    NOMBRE VARCHAR2(50) CONSTRAINT EMP_CRAM_NOM_NN NOT NULL,
    APELLIDO VARCHAR2(50) CONSTRAINT EMP_CRAM_APE_NN NOT NULL,
    PUESTO VARCHAR2(45),
    FECHA_CONTRATACION DATE CONSTRAINT EMP_CRAM_FC_NN NOT NULL,
    CORREO VARCHAR2(60) CONSTRAINT EMP_CRAM_COR_UK UNIQUE,
    CONSTRAINT BIB_CRAM_EMP_CRAM_FK FOREIGN KEY (ID_BIBLIOTECA) REFERENCES BIBLIOTECAS_CRAM(ID_BIBLIOTECA)
);

--TALBA LIBROS-[*]
CREATE TABLE LIBROS_CRAM(
    ISBN NUMBER(13) CONSTRAINT LIB_CRAM_PK PRIMARY KEY,
    TITULO VARCHAR2(100) CONSTRAINT LIB_CRAM_TIT_NN NOT NULL,
    FECHA_PUBLICACION DATE,
    ID_EDITORIAL NUMBER(6) CONSTRAINT LIB_CRAM_EDIT_NN NOT NULL,
    PRECIO_LISTA NUMBER(6) CONSTRAINT LIB_CRAM_PL_CK CHECK (PRECIO_LISTA >= 0),
    PRECIO_AMAZON NUMBER(6) CONSTRAINT LIB_CRAM_PA_CK CHECK (PRECIO_AMAZON >= 0),
    CALIFICACION_AMAZON NUMBER(3,1) CONSTRAINT LIB_CRAM_CA_CK CHECK (CALIFICACION_AMAZON BETWEEN 0 AND 5),
    CONSTRAINT EDIT_CRAM_LIB_CRAM_FK FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIALES_CRAM(ID_EDITORIAL)
);

--TABLA LIBROS_POR_AUTOR-[*]
CREATE TABLE LIBROS_POR_AUTOR_CRAM(
    ID_AUTOR NUMBER(6),
    ISBN NUMBER(13),
    CONSTRAINT LIB_AUT_CRAM_PK PRIMARY KEY (ID_AUTOR, ISBN),
    CONSTRAINT AUT_CRAM_LIB_AUT_CRAM_FK FOREIGN KEY (ID_AUTOR) REFERENCES AUTORES_CRAM(ID_AUTOR),
    CONSTRAINT LIB_CRAM_LIB_AUT_CRAM_FK FOREIGN KEY (ISBN) REFERENCES LIBROS_CRAM(ISBN)
);

--TABLA LIBROS_POR_CATEGORIA
CREATE TABLE LIBROS_POR_CATEGORIA_CRAM(
    ID_CATEGORIA NUMBER(4),
    ISBN NUMBER(13),
    CONSTRAINT LIB_CAT_CRAM_PK PRIMARY KEY (ID_CATEGORIA, ISBN),
    CONSTRAINT CAT_CRAM_LIB_CAT_CRAM_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS_CRAM(ID_CATEGORIA),
    CONSTRAINT LIB_CRAM_LIB_CAT_CRAM_FK FOREIGN KEY (ISBN) REFERENCES LIBROS_CRAM(ISBN)
);

--TABLA LIBROS_EN_BIBLIOTECA
CREATE TABLE LIBROS_EN_BIBLIOTECA_CRAM(
    ID_BIBLIOTECA NUMBER(6),
    ISBN NUMBER(13),
    CANTIDAD_EN_STOCK NUMBER CONSTRAINT LEB_CRAM_STOCK_CK CHECK (CANTIDAD_EN_STOCK >= 0),
    CONSTRAINT LEB_CRAM_PK PRIMARY KEY (ID_BIBLIOTECA, ISBN),
    CONSTRAINT BIB_CRAM_LEB_CRAM_FK FOREIGN KEY (ID_BIBLIOTECA) REFERENCES BIBLIOTECAS_CRAM(ID_BIBLIOTECA),
    CONSTRAINT LIB_CRAM_LEB_CRAM_FK FOREIGN KEY (ISBN) REFERENCES LIBROS_CRAM(ISBN)
);

--TABLA PRESTAMOS
CREATE TABLE PRESTAMOS_CRAM(
    ID_PRESTAMO NUMBER(6) CONSTRAINT PRE_CRAM_PK PRIMARY KEY,
    ID_MIEMBRO NUMBER(6) CONSTRAINT PRE_CRAM_MIE_NN NOT NULL,
    ISBN NUMBER(13) CONSTRAINT PRE_CRAM_ISBN_NN NOT NULL,
    ID_BIBLIOTECA NUMBER(6) CONSTRAINT PRE_CRAM_BIB_NN NOT NULL,
    FECHA_PRESTAMO DATE CONSTRAINT PRE_CRAM_FP_NN NOT NULL,
    FECHA_LIMITE DATE CONSTRAINT PRE_CRAM_FL_NN NOT NULL,
    FECHA_DEVOLUCION DATE,
    ESTADO VARCHAR2(20) CONSTRAINT PRE_CRAM_EST_CK CHECK (ESTADO IN ('Activo','Devuelto','Vencido')),
    CONSTRAINT MIE_CRAM_PRE_CRAM_FK FOREIGN KEY (ID_MIEMBRO) REFERENCES MIEMBROS_CRAM(ID_MIEMBRO),
    CONSTRAINT LIB_CRAM_PRE_CRAM_FK FOREIGN KEY (ISBN) REFERENCES LIBROS_CRAM(ISBN),
    CONSTRAINT BIB_CRAM_PRE_CRAM_FK FOREIGN KEY (ID_BIBLIOTECA) REFERENCES BIBLIOTECAS_CRAM(ID_BIBLIOTECA)
);

--TABLA RESERVACIONES
CREATE TABLE RESERVACIONES_CRAM(
    ID_RESERVACION NUMBER(6) CONSTRAINT RES_CRAM_PK PRIMARY KEY,
    ID_MIEMBRO NUMBER(6) CONSTRAINT RES_CRAM_MIE_NN NOT NULL,
    ISBN NUMBER(13) CONSTRAINT RES_CRAM_ISBN_NN NOT NULL,
    FECHA_RESERVACION DATE CONSTRAINT RES_CRAM_FR_NN NOT NULL,
    FECHA_EXPIRACION DATE,
    ESTADO VARCHAR2(20) CONSTRAINT RES_CRAM_EST_CK CHECK (ESTADO IN ('Pendiente','Completada','Cancelada')),
    CONSTRAINT MIE_CRAM_RES_CRAM_FK FOREIGN KEY (ID_MIEMBRO) REFERENCES MIEMBROS_CRAM(ID_MIEMBRO),
    CONSTRAINT LIB_CRAM_RES_CRAM_FK FOREIGN KEY (ISBN) REFERENCES LIBROS_CRAM(ISBN)
);

--TABLA MULTAS
CREATE TABLE MULTAS_CRAM(
    ID_MULTA NUMBER(6) CONSTRAINT MUL_CRAM_PK PRIMARY KEY,
    ID_PRESTAMO NUMBER(6) CONSTRAINT MUL_CRAM_PRE_NN NOT NULL,
    ID_MIEMBRO NUMBER(6) CONSTRAINT MUL_CRAM_MIE_NN NOT NULL,
    MONTO NUMBER(8) CONSTRAINT MUL_CRAM_MON_CK CHECK (MONTO >= 0),
    FECHA_MULTA DATE CONSTRAINT MUL_CRAM_FM_NN NOT NULL,
    PAGADA CHAR(1) CONSTRAINT MUL_CRAM_PAG_CK CHECK (PAGADA IN ('S','N')),
    FECHA_PAGO DATE,
    CONSTRAINT PRE_CRAM_MUL_CRAM_FK FOREIGN KEY (ID_PRESTAMO) REFERENCES PRESTAMOS_CRAM(ID_PRESTAMO),
    CONSTRAINT MIE_CRAM_MUL_CRAM_FK FOREIGN KEY (ID_MIEMBRO) REFERENCES MIEMBROS_CRAM(ID_MIEMBRO)
);

--TABLA SOLICITUDES
CREATE TABLE SOLICITUDES_CRAM(
    ID_SOLICITUD NUMBER(6) CONSTRAINT SOL_CRAM_PK PRIMARY KEY,
    ID_MIEMBRO NUMBER(6) CONSTRAINT SOL_CRAM_MIE_NN NOT NULL,
    ISBN NUMBER(13) CONSTRAINT SOL_CRAM_ISBN_NN NOT NULL,
    FECHA_SOLICITUD DATE CONSTRAINT SOL_CRAM_FS_NN NOT NULL,
    FECHA_LOCALIZADO DATE,
    OTROS_DETALLES VARCHAR2(150),
    CONSTRAINT MIE_CRAM_SOL_CRAM_FK FOREIGN KEY (ID_MIEMBRO) REFERENCES MIEMBROS_CRAM(ID_MIEMBRO),
    CONSTRAINT LIB_CRAM_SOL_CRAM_FK FOREIGN KEY (ISBN) REFERENCES LIBROS_CRAM(ISBN)
);


-- -------------------------------------------------------
-- SECUENCIAS
-- -------------------------------------------------------

CREATE SEQUENCE DIR_CRAM_ID_DIR_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE NOCACHE;

CREATE SEQUENCE EDIT_CRAM_ID_EDIT_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE NOCACHE;

CREATE SEQUENCE AUT_CRAM_ID_AUT_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE NOCACHE;

CREATE SEQUENCE CAT_CRAM_ID_CAT_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 9999 NOCYCLE NOCACHE;

CREATE SEQUENCE MIE_CRAM_ID_MIE_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE NOCACHE;

CREATE SEQUENCE BIB_CRAM_ID_BIB_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE NOCACHE;

CREATE SEQUENCE EMP_CRAM_ID_EMP_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE NOCACHE;

CREATE SEQUENCE PRE_CRAM_ID_PRE_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE NOCACHE;

CREATE SEQUENCE RES_CRAM_ID_RES_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE NOCACHE;

CREATE SEQUENCE MUL_CRAM_ID_MUL_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE NOCACHE;

CREATE SEQUENCE SOL_CRAM_ID_SOL_SEQ
INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE NOCACHE;


-- -------------------------------------------------------
-- INDICES
-- -------------------------------------------------------

CREATE INDEX IDX_MIE_CRAM_APELLIDO ON MIEMBROS_CRAM(APELLIDO);
CREATE INDEX IDX_MIE_CRAM_CORREO ON MIEMBROS_CRAM(CORREO);
CREATE INDEX IDX_MIE_CRAM_ID_DIR ON MIEMBROS_CRAM(ID_DIRECCION);

CREATE INDEX IDX_BIB_CRAM_NOMBRE ON BIBLIOTECAS_CRAM(NOMBRE_BIBLIOTECA);
CREATE INDEX IDX_BIB_CRAM_ID_DIR ON BIBLIOTECAS_CRAM(ID_DIRECCION);

CREATE INDEX IDX_EMP_CRAM_APELLIDO ON EMPLEADOS_CRAM(APELLIDO);
CREATE INDEX IDX_EMP_CRAM_ID_BIB ON EMPLEADOS_CRAM(ID_BIBLIOTECA);

CREATE INDEX IDX_LIB_CRAM_TITULO ON LIBROS_CRAM(TITULO);
CREATE INDEX IDX_LIB_CRAM_ID_EDIT ON LIBROS_CRAM(ID_EDITORIAL);

CREATE INDEX IDX_PRE_CRAM_ID_MIE ON PRESTAMOS_CRAM(ID_MIEMBRO);
CREATE INDEX IDX_PRE_CRAM_ISBN ON PRESTAMOS_CRAM(ISBN);
CREATE INDEX IDX_PRE_CRAM_ESTADO ON PRESTAMOS_CRAM(ESTADO);

CREATE INDEX IDX_MUL_CRAM_ID_PRE ON MULTAS_CRAM(ID_PRESTAMO);
CREATE INDEX IDX_MUL_CRAM_PAGADA ON MULTAS_CRAM(PAGADA);

CREATE INDEX IDX_RES_CRAM_ID_MIE ON RESERVACIONES_CRAM(ID_MIEMBRO);
CREATE INDEX IDX_RES_CRAM_ISBN ON RESERVACIONES_CRAM(ISBN);


-- -------------------------------------------------------
-- SINONIMOS
-- -------------------------------------------------------

CREATE SYNONYM DIRECCIONES FOR DIRECCIONES_CRAM;
CREATE SYNONYM EDITORIALES FOR EDITORIALES_CRAM;
CREATE SYNONYM AUTORES FOR AUTORES_CRAM;
CREATE SYNONYM CATEGORIAS FOR CATEGORIAS_CRAM;
CREATE SYNONYM MIEMBROS FOR MIEMBROS_CRAM;
CREATE SYNONYM BIBLIOTECAS FOR BIBLIOTECAS_CRAM;
CREATE SYNONYM EMPLEADOS FOR EMPLEADOS_CRAM;
CREATE SYNONYM LIBROS FOR LIBROS_CRAM;
CREATE SYNONYM LIBROS_POR_AUTOR FOR LIBROS_POR_AUTOR_CRAM;
CREATE SYNONYM LIBROS_POR_CATEGORIA FOR LIBROS_POR_CATEGORIA_CRAM;
CREATE SYNONYM LIBROS_EN_BIBLIOTECA FOR LIBROS_EN_BIBLIOTECA_CRAM;
CREATE SYNONYM PRESTAMOS FOR PRESTAMOS_CRAM;
CREATE SYNONYM RESERVACIONES FOR RESERVACIONES_CRAM;
CREATE SYNONYM MULTAS FOR MULTAS_CRAM;
CREATE SYNONYM SOLICITUDES FOR SOLICITUDES_CRAM;