------------------------
--Tablas sin fk---------
------------------------
CREATE TABLE DIRECCIONES_CRAM(
    ID_DIRECCION NUMBER(6) CONSTRAINT DIR_CRAM_PK PRIMARY KEY,
    NUMERO_EDIFICIO NUMBER(5),
    NUMERO_CALLE NUMBER(5) CONSTRAINT DIR_CRAM_NUM_CAL_NN NOT NULL,
    AREA_LOCALIDAD VARCHAR2(100),
    CIUDAD VARCHAR2(50) CONSTRAINT DIR_CRAM_CIU_NN NOT NULL,
    CODIGO_POSTAL NUMBER(6),
    ESTADO VARCHAR2(50),
    PAIS VARCHAR2(50) CONSTRAINT DIR_CRAM_PAI_NN NOT NULL,
    OTROS_DETALLES VARCHAR2(150)
);
