--SYSTEM
--usuario creado
CREATE USER LIBRERIA IDENTIFIED BY "oracle";

--permisos otorgados
GRANT
	CREATE SESSION,
	ALTER SESSION,
	ALTER SYSTEM,
	CREATE TABLE,
	CREATE TABLESPACE,
	UNLIMITED TABLESPACE
TO LIBRERIA;

--mas permisos utiles 
GRANT SELECT ANY TABLE TO "LIBRERIA";
GRANT UPDATE ANY TABLE TO "LIBRERIA";

GRANT CREATE SEQUENCE TO "LIBRERIA";
GRANT CREATE SYNONYM TO "LIBRERIA";
--El grant de create view
GRANT CREATE VIEW TO "LIBRERIA";

SELECT privilege
FROM dba_sys_privs
WHERE grantee ='LIBRERIA';
